syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.datasources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaFleetManagementCollector version is 0
message GrafanaFleetManagementCollector {
  // Type of the collector (ALLOY or OTEL)
  string collector_type = 1 [json_name = "collector_type"];

  // Whether remote configuration for the collector is enabled or not. If the
  // collector is disabled, it will receive empty configurations from the Fleet
  // Management service
  bool enabled = 2;

  // ID of the collector
  string id = 3;

  // Local attributes for the collector
  map<string, string> local_attributes = 4 [json_name = "local_attributes"];

  // Remote attributes for the collector
  map<string, string> remote_attributes = 5 [json_name = "remote_attributes"];

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;
}

// GrafanaFleetManagementCollectors version is 0
message GrafanaFleetManagementCollectors {
  // List of collectors
  repeated Collectors collectors = 1;

  google.protobuf.Value for_each = 2 [json_name = "for_each"];

  repeated string depends_on = 3 [json_name = "depends_on"];

  int32 count = 4;

  string provider = 5;

  terraform.v1.Lifecycle lifecycle = 6;

  message Collectors {
    // collector_type: string
    string collector_type = 1 [json_name = "collector_type"];

    // enabled: bool
    bool enabled = 2;

    // id: string
    string id = 3;

    // local_attributes: map of string
    map<string, string> local_attributes = 4 [json_name = "local_attributes"];

    // remote_attributes: map of string
    map<string, string> remote_attributes = 5 [json_name = "remote_attributes"];
  }
}
