syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.datasources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaK6LoadTest version is 0
message GrafanaK6LoadTest {
  // Identifier of a baseline test run used for results comparison.
  string baseline_test_run_id = 1 [json_name = "baseline_test_run_id"];

  // The date when the load test was created.
  string created = 2;

  // Numeric identifier of the load test.
  string id = 3;

  // Identifier of the k6 version used to run the test.
  string k6_version = 4 [json_name = "k6_version"];

  // Human-friendly identifier of the load test.
  string name = 5;

  // The identifier of the project this load test belongs to.
  string project_id = 6 [json_name = "project_id"];

  // The k6 test script content.
  string script = 7;

  // The date when the load test was last updated.
  string updated = 8;

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}

// GrafanaK6LoadTests version is 0
message GrafanaK6LoadTests {
  // The identifier of the project the load tests belong to. This is set to the same
  // as the project_id.
  string id = 1;

  repeated LoadTests load_tests = 2 [json_name = "load_tests"];

  // Human-friendly identifier of the load test.
  string name = 3;

  // The identifier of the project the load tests belong to.
  string project_id = 4 [json_name = "project_id"];

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;

  message LoadTests {
    // baseline_test_run_id: string
    string baseline_test_run_id = 1 [json_name = "baseline_test_run_id"];

    // created: string
    string created = 2;

    // id: string
    string id = 3;

    // k6_version: string
    string k6_version = 4 [json_name = "k6_version"];

    // name: string
    string name = 5;

    // project_id: string
    string project_id = 6 [json_name = "project_id"];

    // script: string
    string script = 7;

    // updated: string
    string updated = 8;
  }
}

// GrafanaK6Project version is 0
message GrafanaK6Project {
  // The date when the project was created.
  string created = 1;

  // The Grafana folder uid.
  string grafana_folder_uid = 2 [json_name = "grafana_folder_uid"];

  // Numeric identifier of the project.
  string id = 3;

  // Whether this project is the default for running tests when no explicit project
  // identifier is provided.
  bool is_default = 4 [json_name = "is_default"];

  // Human-friendly identifier of the project.
  string name = 5;

  // The date when the project was last updated.
  string updated = 6;

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// GrafanaK6ProjectAllowedLoadZones version is 0
message GrafanaK6ProjectAllowedLoadZones {
  // List of allowed private k6 load zone IDs for this project.
  repeated string allowed_load_zones = 1 [json_name = "allowed_load_zones"];

  // The identifier of the project. This is set to the same as the project_id.
  string id = 2;

  // The identifier of the project to retrieve private allowed load zones for.
  string project_id = 3 [json_name = "project_id"];

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;
}

// GrafanaK6ProjectLimits version is 0
message GrafanaK6ProjectLimits {
  // Maximum duration of a test in seconds.
  int64 duration_max_per_test = 1 [json_name = "duration_max_per_test"];

  // The identifier of the project limits. This is set to the same as the project_id.
  string id = 2;

  // The identifier of the project to get limits for.
  string project_id = 3 [json_name = "project_id"];

  // Maximum number of concurrent browser virtual users (VUs) used in one test.
  int64 vu_browser_max_per_test = 4 [json_name = "vu_browser_max_per_test"];

  // Maximum number of concurrent virtual users (VUs) used in one test.
  int64 vu_max_per_test = 5 [json_name = "vu_max_per_test"];

  // Maximum amount of virtual user hours (VU/h) used per one calendar month.
  int64 vuh_max_per_month = 6 [json_name = "vuh_max_per_month"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// GrafanaK6Projects version is 0
message GrafanaK6Projects {
  // Human-friendly identifier of the project. This is set to the same as name.
  string id = 1;

  // Human-friendly identifier of the project.
  string name = 2;

  repeated Projects projects = 3;

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;

  message Projects {
    // created: string
    string created = 1;

    // grafana_folder_uid: string
    string grafana_folder_uid = 2 [json_name = "grafana_folder_uid"];

    // id: string
    string id = 3;

    // is_default: bool
    bool is_default = 4 [json_name = "is_default"];

    // name: string
    string name = 5;

    // updated: string
    string updated = 6;
  }
}

// GrafanaK6Schedule version is 0
message GrafanaK6Schedule {
  // The email of the user who created the schedule.
  string created_by = 1 [json_name = "created_by"];

  // Whether the schedule is deactivated.
  bool deactivated = 2;

  // Numeric identifier of the schedule.
  string id = 3;

  // The identifier of the load test to retrieve the schedule for.
  string load_test_id = 4 [json_name = "load_test_id"];

  // The next scheduled execution time.
  string next_run = 5 [json_name = "next_run"];

  // The start time for the schedule (RFC3339 format).
  string starts = 6;

  repeated Cron cron = 7;

  repeated RecurrenceRule recurrence_rule = 8 [json_name = "recurrence_rule"];

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;

  message Cron {
    // A cron expression with exactly 5 entries, or an alias. The allowed aliases are:
    // `@yearly`, `@annually`, `@monthly`, `@weekly`, `@daily`, `@hourly`.
    string schedule = 1;

    // The timezone of the cron expression. For example, `UTC` or `Europe/London`.
    string timezone = 2;
  }

  message RecurrenceRule {
    // The weekdays when the 'WEEKLY' recurrence will be applied (e.g., ['MO', 'WE',
    // 'FR']). Cannot be set for other frequencies.
    repeated string byday = 1;

    // How many times the recurrence will repeat.
    int64 count = 2;

    // The frequency of the schedule (HOURLY, DAILY, WEEKLY, MONTHLY).
    string frequency = 3;

    // The interval between each frequency iteration (e.g., 2 = every 2 hours for
    // HOURLY).
    int64 interval = 4;

    // The end time for the recurrence (RFC3339 format).
    string until = 5;
  }
}

// GrafanaK6Schedules version is 0
message GrafanaK6Schedules {
  // The identifier for this data source.
  string id = 1;

  // List of k6 schedules.
  repeated Schedules schedules = 2;

  google.protobuf.Value for_each = 3 [json_name = "for_each"];

  repeated string depends_on = 4 [json_name = "depends_on"];

  int32 count = 5;

  string provider = 6;

  terraform.v1.Lifecycle lifecycle = 7;

  message Schedules {
    // created_by: string
    string created_by = 1 [json_name = "created_by"];

    // cron: object
    Cron cron = 2;

    // deactivated: bool
    bool deactivated = 3;

    // id: string
    string id = 4;

    // load_test_id: string
    string load_test_id = 5 [json_name = "load_test_id"];

    // next_run: string
    string next_run = 6 [json_name = "next_run"];

    // recurrence_rule: object
    RecurrenceRule recurrence_rule = 7 [json_name = "recurrence_rule"];

    // starts: string
    string starts = 8;

    message Cron {
      // schedule: string
      string schedule = 1;

      // timezone: string
      string timezone = 2;
    }

    message RecurrenceRule {
      // byday: list of string
      repeated string byday = 1;

      // count: number
      int64 count = 2;

      // frequency: string
      string frequency = 3;

      // interval: number
      int64 interval = 4;

      // until: string
      string until = 5;
    }
  }
}
