syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaCloudAccessPolicy version is 0
message GrafanaCloudAccessPolicy {
  // Creation date of the access policy.
  string created_at = 1 [json_name = "created_at"];

  // Display name of the access policy. Defaults to the name.
  string display_name = 2 [json_name = "display_name"];

  string id = 3;

  // Name of the access policy.
  string name = 4;

  // ID of the access policy.
  string policy_id = 5 [json_name = "policy_id"];

  // Region where the API is deployed. Generally where the stack is deployed. Use the
  // region list API to get the list of available regions:
  // com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-regions.
  string region = 6;

  // Scopes of the access policy. See
  // ity-and-account-management/authentication-and-permissions/access-policies/#scopes
  // for possible values.
  repeated string scopes = 7;

  // Last update date of the access policy.
  string updated_at = 8 [json_name = "updated_at"];

  repeated Conditions conditions = 9;

  repeated Realm realm = 10;

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;

  message Conditions {
    // Conditions that apply to the access policy,such as IP Allow lists.
    repeated string allowed_subnets = 1 [json_name = "allowed_subnets"];
  }

  message Realm {
    // The identifier of the org or stack. For orgs, this is the slug, for stacks, this
    // is the stack ID.
    string identifier = 1;

    // Whether a policy applies to a Cloud org or a specific stack. Should be one of
    // `org` or `stack`.
    string type = 2;

    repeated LabelPolicy label_policy = 3 [json_name = "label_policy"];

    message LabelPolicy {
      // The label selector to match in metrics or logs query. Should be in PromQL or
      // LogQL format.
      string selector = 1;
    }
  }
}

// GrafanaCloudAccessPolicyRotatingToken version is 0
message GrafanaCloudAccessPolicyRotatingToken {
  // ID of the access policy for which to create a token.
  string access_policy_id = 1 [json_name = "access_policy_id"];

  // Creation date of the access policy token.
  string created_at = 2 [json_name = "created_at"];

  // Deletes the token in Grafana Cloud when the resource is destroyed in Terraform,
  // instead of leaving it to expire at its `expires_at` time. Use it with `lifecycle
  // { create_before_destroy = true }` to make sure that the new token is created
  // before the old one is deleted. Defaults to `false`.
  bool delete_on_destroy = 3 [json_name = "delete_on_destroy"];

  // Display name of the access policy token. Defaults to the name.
  string display_name = 4 [json_name = "display_name"];

  // Duration of the window before expiring where the token can be rotated (e.g.
  // '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h'
  // (hours).
  string early_rotation_window = 5 [json_name = "early_rotation_window"];

  // Duration after which the token will expire (e.g. '24h', '30m', '1h30m'). Valid
  // units are 's' (seconds), 'm' (minutes) and 'h' (hours).
  string expire_after = 6 [json_name = "expire_after"];

  // Expiration date of the access policy token.
  string expires_at = 7 [json_name = "expires_at"];

  string id = 8;

  // Name of the access policy token.
  string name = 9;

  // Prefix for the name of the access policy token. The actual name will be stored in
  // the computed field `name`, which will be in the format
  // '<name_prefix>-<expiration_timestamp>'
  string name_prefix = 10 [json_name = "name_prefix"];

  // Signals that the token is either expired or within the period to be early
  // rotated.
  bool ready_for_rotation = 11 [json_name = "ready_for_rotation"];

  // Region of the access policy. Should be set to the same region as the access
  // policy. Use the region list API to get the list of available regions:
  // com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-regions.
  string region = 12;

  string token = 13;

  // Last update date of the access policy token.
  string updated_at = 14 [json_name = "updated_at"];

  google.protobuf.Value for_each = 15 [json_name = "for_each"];

  repeated string depends_on = 16 [json_name = "depends_on"];

  int32 count = 17;

  string provider = 18;

  terraform.v1.Lifecycle lifecycle = 19;
}

// GrafanaCloudAccessPolicyToken version is 0
message GrafanaCloudAccessPolicyToken {
  // ID of the access policy for which to create a token.
  string access_policy_id = 1 [json_name = "access_policy_id"];

  // Creation date of the access policy token.
  string created_at = 2 [json_name = "created_at"];

  // Display name of the access policy token. Defaults to the name.
  string display_name = 3 [json_name = "display_name"];

  // Expiration date of the access policy token. Does not expire by default.
  string expires_at = 4 [json_name = "expires_at"];

  string id = 5;

  // Name of the access policy token.
  string name = 6;

  // Region of the access policy. Should be set to the same region as the access
  // policy. Use the region list API to get the list of available regions:
  // com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-regions.
  string region = 7;

  string token = 8;

  // Last update date of the access policy token.
  string updated_at = 9 [json_name = "updated_at"];

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;
}

// GrafanaCloudIntegration version is 0
message GrafanaCloudIntegration {
  // Whether alerts are enabled for this integration.
  bool alerts_enabled = 1 [json_name = "alerts_enabled"];

  // The dashboard folder associated with this integration.
  string dashboard_folder = 2 [json_name = "dashboard_folder"];

  // The Terraform resource ID. Set to the integration slug.
  string id = 3;

  // The version of the installed integration.
  string installed_version = 4 [json_name = "installed_version"];

  // The latest version available for this integration.
  string latest_version = 5 [json_name = "latest_version"];

  // The display name of the integration.
  string name = 6;

  // The slug of the integration to install (e.g., 'docker', 'linux-node').
  string slug = 7;

  google.protobuf.Value for_each = 8 [json_name = "for_each"];

  repeated string depends_on = 9 [json_name = "depends_on"];

  int32 count = 10;

  string provider = 11;

  terraform.v1.Lifecycle lifecycle = 12;
}

// GrafanaCloudOrgMember version is 0
message GrafanaCloudOrgMember {
  string id = 1;

  // The slug or ID of the organization.
  string org = 2;

  // Whether the user should receive billing emails.
  bool receive_billing_emails = 3 [json_name = "receive_billing_emails"];

  // The role to assign to the user in the organization.
  string role = 4;

  // Username or ID of the user to add to the org's members.
  string user = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;
}

// GrafanaCloudPluginInstallation version is 0
message GrafanaCloudPluginInstallation {
  string id = 1;

  // Slug of the plugin to be installed.
  string slug = 2;

  // The stack id to which the plugin should be installed.
  string stack_slug = 3 [json_name = "stack_slug"];

  // Version of the plugin to be installed. Defaults to 'latest' and installs the most
  // recent version. Terraform will detect new version as drift for plan/apply.
  // Defaults to `latest`.
  string version = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// GrafanaCloudPrivateDataSourceConnectNetwork version is 0
message GrafanaCloudPrivateDataSourceConnectNetwork {
  // Creation date of the private data source connect network.
  string created_at = 1 [json_name = "created_at"];

  // Display name of the PDC network. Defaults to the name.
  string display_name = 2 [json_name = "display_name"];

  string id = 3;

  // Name of the PDC network.**Note:** The name must be lowercase and can contain
  // hyphens or underscores. See full requirements here:
  // .com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#request-body
  string name = 4;

  // ID of the private data source connect network.
  string pdc_network_id = 5 [json_name = "pdc_network_id"];

  // The region where your stack is deployed. Use the instances list API to get the
  // region for your instance - use the regionSlug property:
  // a.com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-stacks
  string region = 6;

  // The identifier of the stack.
  string stack_identifier = 7 [json_name = "stack_identifier"];

  // Last update date of the private data source connect network.
  string updated_at = 8 [json_name = "updated_at"];

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}

// GrafanaCloudPrivateDataSourceConnectNetworkToken version is 0
message GrafanaCloudPrivateDataSourceConnectNetworkToken {
  // Creation date of the private data source network token.
  string created_at = 1 [json_name = "created_at"];

  // Display name of the private data source network token. Defaults to the name.
  string display_name = 2 [json_name = "display_name"];

  // Expiration date of the private data source network token. Does not expire by
  // default.
  string expires_at = 3 [json_name = "expires_at"];

  string id = 4;

  // Name of the private data source network token.
  string name = 5;

  // ID of the private data source network for which to create a token.
  string pdc_network_id = 6 [json_name = "pdc_network_id"];

  // Region of the private data source network. Should be set to the same region as
  // the private data source network. Use the region list API to get the list of
  // available regions:
  // com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-regions.
  string region = 7;

  string token = 8;

  // Last update date of the private data source network token.
  string updated_at = 9 [json_name = "updated_at"];

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;
}

// GrafanaCloudProviderAwsAccount version is 0
message GrafanaCloudProviderAwsAccount {
  // The Terraform Resource ID. This has the format "{{ stack_id }}:{{ resource_id
  // }}".
  string id = 1;

  // An optional human-readable name for this AWS Account resource.
  string name = 2;

  // A set of regions that this AWS Account resource applies to.
  repeated string regions = 3;

  // The ID given by the Grafana Cloud Provider API to this AWS Account resource.
  string resource_id = 4 [json_name = "resource_id"];

  // An IAM Role ARN string to represent with this AWS Account resource.
  string role_arn = 5 [json_name = "role_arn"];

  // The StackID of the Grafana Cloud instance. Part of the Terraform Resource ID.
  string stack_id = 6 [json_name = "stack_id"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// GrafanaCloudProviderAwsCloudwatchScrapeJob version is 0
message GrafanaCloudProviderAwsCloudwatchScrapeJob {
  // The ID assigned by the Grafana Cloud Provider API to an AWS Account resource that
  // should be associated with this CloudWatch Scrape Job. This can be provided by the
  // `resource_id` attribute of the `grafana_cloud_provider_aws_account` resource.
  string aws_account_resource_id = 1 [json_name = "aws_account_resource_id"];

  // When the AWS CloudWatch Scrape Job is disabled, this will show the reason that it
  // is in that state.
  string disabled_reason = 2 [json_name = "disabled_reason"];

  // Whether the AWS CloudWatch Scrape Job is enabled or not. Defaults to `true`.
  bool enabled = 3;

  // When enabled, AWS resource tags are exported as Prometheus labels to metrics
  // formatted as `aws_<service_name>_info`. Defaults to `true`.
  bool export_tags = 4 [json_name = "export_tags"];

  // The Terraform Resource ID. This has the format "{{ stack_id }}:{{ name }}".
  string id = 5;

  // The name of the AWS CloudWatch Scrape Job. Part of the Terraform Resource ID.
  string name = 6;

  // A subset of the regions that are configured in the associated AWS Account
  // resource to apply to this scrape job. If not set or empty, all of the Account
  // resource's regions are scraped.
  repeated string regions_subset_override = 7 [json_name = "regions_subset_override"];

  // The Stack ID of the Grafana Cloud instance. Part of the Terraform Resource ID.
  string stack_id = 8 [json_name = "stack_id"];

  // A set of static labels to add to all metrics exported by this scrape job.
  map<string, string> static_labels = 9 [json_name = "static_labels"];

  repeated CustomNamespace custom_namespace = 10 [json_name = "custom_namespace"];

  repeated Service service = 11;

  google.protobuf.Value for_each = 12 [json_name = "for_each"];

  repeated string depends_on = 13 [json_name = "depends_on"];

  int32 count = 14;

  string provider = 15;

  terraform.v1.Lifecycle lifecycle = 16;

  message CustomNamespace {
    // The name of the custom namespace to scrape.
    string name = 1;

    // The interval in seconds to scrape the custom namespace. Defaults to `300`.
    int64 scrape_interval_seconds = 2 [json_name = "scrape_interval_seconds"];

    repeated Metric metric = 3;

    message Metric {
      // The name of the metric to scrape.
      string name = 1;

      // A set of statistics to scrape.
      repeated string statistics = 2;
    }
  }

  message Service {
    // The name of the service to scrape. See
    // ud/monitor-infrastructure/monitor-cloud-provider/aws/cloudwatch-metrics/services/
    // for supported services.
    string name = 1;

    // The interval in seconds to scrape the service. See
    // ud/monitor-infrastructure/monitor-cloud-provider/aws/cloudwatch-metrics/services/
    // for supported scrape intervals. Defaults to `300`.
    int64 scrape_interval_seconds = 2 [json_name = "scrape_interval_seconds"];

    // A set of tags to add to all metrics exported by this scrape job, for use in
    // PromQL queries.
    repeated string tags_to_add_to_metrics = 3 [json_name = "tags_to_add_to_metrics"];

    repeated Metric metric = 4;

    repeated ResourceDiscoveryTagFilter resource_discovery_tag_filter = 5 [json_name = "resource_discovery_tag_filter"];

    message Metric {
      // The name of the metric to scrape.
      string name = 1;

      // A set of statistics to scrape.
      repeated string statistics = 2;
    }

    message ResourceDiscoveryTagFilter {
      // The key of the tag filter.
      string key = 1;

      // The value of the tag filter.
      string value = 2;
    }
  }
}

// GrafanaCloudProviderAwsResourceMetadataScrapeJob version is 0
message GrafanaCloudProviderAwsResourceMetadataScrapeJob {
  // The ID assigned by the Grafana Cloud Provider API to an AWS Account resource that
  // should be associated with this Resource Metadata Scrape Job. This can be provided
  // by the `resource_id` attribute of the `grafana_cloud_provider_aws_account`
  // resource.
  string aws_account_resource_id = 1 [json_name = "aws_account_resource_id"];

  // When the AWS Resource Metadata Scrape Job is disabled, this will show the reason
  // that it is in that state.
  string disabled_reason = 2 [json_name = "disabled_reason"];

  // Whether the AWS Resource Metadata Scrape Job is enabled or not. Defaults to
  // `true`.
  bool enabled = 3;

  // The Terraform Resource ID. This has the format "{{ stack_id }}:{{ name }}".
  string id = 4;

  // The name of the AWS Resource Metadata Scrape Job. Part of the Terraform Resource
  // ID.
  string name = 5;

  // A subset of the regions that are configured in the associated AWS Account
  // resource to apply to this scrape job. If not set or empty, all of the Account
  // resource's regions are scraped.
  repeated string regions_subset_override = 6 [json_name = "regions_subset_override"];

  // The Stack ID of the Grafana Cloud instance. Part of the Terraform Resource ID.
  string stack_id = 7 [json_name = "stack_id"];

  // A set of static labels to add to all metrics exported by this scrape job.
  map<string, string> static_labels = 8 [json_name = "static_labels"];

  repeated Service service = 9;

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;

  message Service {
    // The name of the service to scrape. See
    // ud/monitor-infrastructure/monitor-cloud-provider/aws/cloudwatch-metrics/services/
    // for supported services.
    string name = 1;

    // The interval in seconds to scrape the service. See
    // ud/monitor-infrastructure/monitor-cloud-provider/aws/cloudwatch-metrics/services/
    // for supported scrape intervals. Defaults to `300`.
    int64 scrape_interval_seconds = 2 [json_name = "scrape_interval_seconds"];

    repeated ResourceDiscoveryTagFilter resource_discovery_tag_filter = 3 [json_name = "resource_discovery_tag_filter"];

    message ResourceDiscoveryTagFilter {
      // The key of the tag filter.
      string key = 1;

      // The value of the tag filter.
      string value = 2;
    }
  }
}

// GrafanaCloudProviderAzureCredential version is 0
message GrafanaCloudProviderAzureCredential {
  // The client ID of the Azure Credential.
  string client_id = 1 [json_name = "client_id"];

  // The client secret of the Azure Credential.
  string client_secret = 2 [json_name = "client_secret"];

  // Whether the Azure Credential is enabled or not. Defaults to `true`.
  bool enabled = 3;

  // The Terraform Resource ID. This has the format "{{ stack_id }}:{{ resource_id
  // }}".
  string id = 4;

  // The name of the Azure Credential.
  string name = 5;

  // The ID given by the Grafana Cloud Provider API to this Azure Credential resource.
  string resource_id = 6 [json_name = "resource_id"];

  // The list of resource tags to add to metrics.
  repeated string resource_tags_to_add_to_metrics = 7 [json_name = "resource_tags_to_add_to_metrics"];

  // The StackID of the Grafana Cloud instance. Part of the Terraform Resource ID.
  string stack_id = 8 [json_name = "stack_id"];

  // A set of static labels to add to all metrics exported using this credential.
  map<string, string> static_labels = 9 [json_name = "static_labels"];

  // The tenant ID of the Azure Credential.
  string tenant_id = 10 [json_name = "tenant_id"];

  repeated AutoDiscoveryConfiguration auto_discovery_configuration = 11 [json_name = "auto_discovery_configuration"];

  repeated ResourceDiscoveryTagFilter resource_discovery_tag_filter = 12 [json_name = "resource_discovery_tag_filter"];

  google.protobuf.Value for_each = 13 [json_name = "for_each"];

  repeated string depends_on = 14 [json_name = "depends_on"];

  int32 count = 15;

  string provider = 16;

  terraform.v1.Lifecycle lifecycle = 17;

  message AutoDiscoveryConfiguration {
    // The list of resource type configurations.
    repeated ResourceTypeConfigurations resource_type_configurations = 1 [json_name = "resource_type_configurations"];

    // The subscription ID of the Azure account.
    string subscription_id = 2 [json_name = "subscription_id"];

    message ResourceTypeConfigurations {
      // metric_configuration: list of object
      repeated MetricConfiguration metric_configuration = 1 [json_name = "metric_configuration"];

      // resource_type_name: string
      string resource_type_name = 2 [json_name = "resource_type_name"];

      message MetricConfiguration {
        // aggregations: list of string
        repeated string aggregations = 1;

        // dimensions: list of string
        repeated string dimensions = 2;

        // name: string
        string name = 3;
      }
    }
  }

  message ResourceDiscoveryTagFilter {
    // The key of the tag filter.
    string key = 1;

    // The value of the tag filter.
    string value = 2;
  }
}

// GrafanaCloudStack version is 0
message GrafanaCloudStack {
  // Allowlist API endpoint that returns the source IP addresses to allow for the
  // Alertmanager instances.
  string alertmanager_allowlist_url = 1 [json_name = "alertmanager_allowlist_url"];

  // Comma-separated list of CNAMEs that can be whitelisted to access the Alertmanager
  // instances (Optional)
  string alertmanager_ip_allow_list_cname = 2 [json_name = "alertmanager_ip_allow_list_cname"];

  // Name of the Alertmanager instance configured for this stack.
  string alertmanager_name = 3 [json_name = "alertmanager_name"];

  // Status of the Alertmanager instance configured for this stack.
  string alertmanager_status = 4 [json_name = "alertmanager_status"];

  // Base URL of the Alertmanager instance configured for this stack.
  string alertmanager_url = 5 [json_name = "alertmanager_url"];

  // User ID of the Alertmanager instance configured for this stack.
  int64 alertmanager_user_id = 6 [json_name = "alertmanager_user_id"];

  // Base URL of the Cloud Provider API for this stack's cluster. This can be used
  // with the `cloud_provider_url` provider config option to manage Cloud Provider
  // resources for this stack.
  string cloud_provider_url = 7 [json_name = "cloud_provider_url"];

  // Name of the cluster where this stack resides.
  string cluster_name = 8 [json_name = "cluster_name"];

  // Slug of the cluster where this stack resides.
  string cluster_slug = 9 [json_name = "cluster_slug"];

  // Base URL of the Connections API for this stack's cluster. This can be used with
  // the `connections_api_url` provider config option to manage Connections resources
  // for this stack.
  string connections_api_url = 10 [json_name = "connections_api_url"];

  // Whether to enable delete protection for the stack, preventing accidental
  // deletion. Defaults to `true`.
  bool delete_protection = 11 [json_name = "delete_protection"];

  // Description of stack.
  string description = 12;

  // Allowlist API endpoint that returns the source IP addresses to allow for the
  // Fleet Management instance.
  string fleet_management_allowlist_url = 13 [json_name = "fleet_management_allowlist_url"];

  // Name of the Fleet Management instance configured for this stack.
  string fleet_management_name = 14 [json_name = "fleet_management_name"];

  // Availability Zone IDs for Fleet Management when using AWS PrivateLink (only for
  // AWS stacks)
  repeated string fleet_management_private_connectivity_info_availability_zone_ids = 15 [
    json_name = "fleet_management_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for Fleet Management when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string fleet_management_private_connectivity_info_availability_zones = 16 [
    json_name = "fleet_management_private_connectivity_info_availability_zones"
  ];

  // Private DNS for Fleet Management when using AWS PrivateLink (only for AWS stacks)
  string fleet_management_private_connectivity_info_private_dns = 17 [
    json_name = "fleet_management_private_connectivity_info_private_dns"
  ];

  // Regions for Fleet Management when using AWS PrivateLink (only for AWS stacks)
  repeated string fleet_management_private_connectivity_info_regions = 18 [
    json_name = "fleet_management_private_connectivity_info_regions"
  ];

  // Service Name for Fleet Management when using AWS PrivateLink (only for AWS
  // stacks)
  string fleet_management_private_connectivity_info_service_name = 19 [
    json_name = "fleet_management_private_connectivity_info_service_name"
  ];

  // Status of the Fleet Management instance configured for this stack.
  string fleet_management_status = 20 [json_name = "fleet_management_status"];

  // Base URL of the Fleet Management instance configured for this stack.
  string fleet_management_url = 21 [json_name = "fleet_management_url"];

  // User ID of the Fleet Management instance configured for this stack.
  int64 fleet_management_user_id = 22 [json_name = "fleet_management_user_id"];

  // Allowlist API endpoint that returns the source IP addresses to allow for the
  // grafana instance.
  string grafanas_allowlist_url = 23 [json_name = "grafanas_allowlist_url"];

  // Comma-separated list of CNAMEs that can be whitelisted to access the grafana
  // instance (Optional)
  string grafanas_ip_allow_list_cname = 24 [json_name = "grafanas_ip_allow_list_cname"];

  // Allowlist API endpoint that returns the source IP addresses to allow for the
  // Graphite instance.
  string graphite_allowlist_url = 25 [json_name = "graphite_allowlist_url"];

  // Comma-separated list of CNAMEs that can be whitelisted to access the Graphite
  // instance (Optional)
  string graphite_ip_allow_list_cname = 26 [json_name = "graphite_ip_allow_list_cname"];

  string graphite_name = 27 [json_name = "graphite_name"];

  // Availability Zone IDs for Graphite when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string graphite_private_connectivity_info_availability_zone_ids = 28 [
    json_name = "graphite_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for Graphite when using AWS PrivateLink (only for AWS stacks)
  repeated string graphite_private_connectivity_info_availability_zones = 29 [
    json_name = "graphite_private_connectivity_info_availability_zones"
  ];

  // Private DNS for Graphite when using AWS PrivateLink (only for AWS stacks)
  string graphite_private_connectivity_info_private_dns = 30 [
    json_name = "graphite_private_connectivity_info_private_dns"
  ];

  // Regions for Graphite when using AWS PrivateLink (only for AWS stacks)
  repeated string graphite_private_connectivity_info_regions = 31 [
    json_name = "graphite_private_connectivity_info_regions"
  ];

  // Service Name for Graphite when using AWS PrivateLink (only for AWS stacks)
  string graphite_private_connectivity_info_service_name = 32 [
    json_name = "graphite_private_connectivity_info_service_name"
  ];

  string graphite_status = 33 [json_name = "graphite_status"];

  string graphite_url = 34 [json_name = "graphite_url"];

  int64 graphite_user_id = 35 [json_name = "graphite_user_id"];

  // The stack id assigned to this stack by Grafana.
  string id = 36;

  // Base URL of the InfluxDB instance configured for this stack. The username is the
  // same as the metrics' (`prometheus_user_id` attribute of this resource). See
  // ana.com/docs/grafana-cloud/send-data/metrics/metrics-influxdb/push-from-telegraf/
  // for docs on how to use this.
  string influx_url = 37 [json_name = "influx_url"];

  // A map of labels to assign to the stack. Label keys and values must match the
  // following regexp: "^[a-zA-Z0-9/\\-._]+$" and stacks cannot have more than 10
  // labels.
  map<string, string> labels = 38;

  // Allowlist API endpoint that returns the source IP addresses to allow for the Logs
  // instance.
  string logs_allowlist_url = 39 [json_name = "logs_allowlist_url"];

  // Comma-separated list of CNAMEs that can be whitelisted to access the Logs
  // instance (Optional)
  string logs_ip_allow_list_cname = 40 [json_name = "logs_ip_allow_list_cname"];

  string logs_name = 41 [json_name = "logs_name"];

  // Availability Zone IDs for Logs when using AWS PrivateLink (only for AWS stacks)
  repeated string logs_private_connectivity_info_availability_zone_ids = 42 [
    json_name = "logs_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for Logs when using AWS PrivateLink (only for AWS stacks)
  repeated string logs_private_connectivity_info_availability_zones = 43 [
    json_name = "logs_private_connectivity_info_availability_zones"
  ];

  // Private DNS for Logs when using AWS PrivateLink (only for AWS stacks)
  string logs_private_connectivity_info_private_dns = 44 [
    json_name = "logs_private_connectivity_info_private_dns"
  ];

  // Regions for Logs when using AWS PrivateLink (only for AWS stacks)
  repeated string logs_private_connectivity_info_regions = 45 [
    json_name = "logs_private_connectivity_info_regions"
  ];

  // Service Name for Logs when using AWS PrivateLink (only for AWS stacks)
  string logs_private_connectivity_info_service_name = 46 [
    json_name = "logs_private_connectivity_info_service_name"
  ];

  string logs_status = 47 [json_name = "logs_status"];

  string logs_url = 48 [json_name = "logs_url"];

  int64 logs_user_id = 49 [json_name = "logs_user_id"];

  // Name of stack. Conventionally matches the url of the instance (e.g.
  // `<stack_slug>.grafana.net`).
  string name = 50;

  // Base URL of the OnCall API instance configured for this stack.
  string oncall_api_url = 51 [json_name = "oncall_api_url"];

  // Organization id to assign to this stack.
  int64 org_id = 52 [json_name = "org_id"];

  // Organization name to assign to this stack.
  string org_name = 53 [json_name = "org_name"];

  // Organization slug to assign to this stack.
  string org_slug = 54 [json_name = "org_slug"];

  // Availability Zone IDs for OTLP when using AWS PrivateLink (only for AWS stacks)
  repeated string otlp_private_connectivity_info_availability_zone_ids = 55 [
    json_name = "otlp_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for OTLP when using AWS PrivateLink (only for AWS stacks)
  repeated string otlp_private_connectivity_info_availability_zones = 56 [
    json_name = "otlp_private_connectivity_info_availability_zones"
  ];

  // Private DNS for OTLP when using AWS PrivateLink (only for AWS stacks)
  string otlp_private_connectivity_info_private_dns = 57 [
    json_name = "otlp_private_connectivity_info_private_dns"
  ];

  // Regions for OTLP when using AWS PrivateLink (only for AWS stacks)
  repeated string otlp_private_connectivity_info_regions = 58 [
    json_name = "otlp_private_connectivity_info_regions"
  ];

  // Service Name for OTLP when using AWS PrivateLink (only for AWS stacks)
  string otlp_private_connectivity_info_service_name = 59 [
    json_name = "otlp_private_connectivity_info_service_name"
  ];

  // Base URL of the OTLP instance configured for this stack. The username is the
  // stack's ID (`id` attribute of this resource). See
  // https://grafana.com/docs/grafana-cloud/send-data/otlp/send-data-otlp/ for docs on
  // how to use this.
  string otlp_url = 60 [json_name = "otlp_url"];

  // Availability Zone IDs for PDC's API when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string pdc_api_private_connectivity_info_availability_zone_ids = 61 [
    json_name = "pdc_api_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for PDC's API when using AWS PrivateLink (only for AWS stacks)
  repeated string pdc_api_private_connectivity_info_availability_zones = 62 [
    json_name = "pdc_api_private_connectivity_info_availability_zones"
  ];

  // Private DNS for PDC's API when using AWS PrivateLink (only for AWS stacks)
  string pdc_api_private_connectivity_info_private_dns = 63 [
    json_name = "pdc_api_private_connectivity_info_private_dns"
  ];

  // Regions for PDC's API when using AWS PrivateLink (only for AWS stacks)
  repeated string pdc_api_private_connectivity_info_regions = 64 [
    json_name = "pdc_api_private_connectivity_info_regions"
  ];

  // Service Name for PDC's API when using AWS PrivateLink (only for AWS stacks)
  string pdc_api_private_connectivity_info_service_name = 65 [
    json_name = "pdc_api_private_connectivity_info_service_name"
  ];

  // Availability Zone IDs for PDC's Gateway when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string pdc_gateway_private_connectivity_info_availability_zone_ids = 66 [
    json_name = "pdc_gateway_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for PDC's Gateway when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string pdc_gateway_private_connectivity_info_availability_zones = 67 [
    json_name = "pdc_gateway_private_connectivity_info_availability_zones"
  ];

  // Private DNS for PDC's Gateway when using AWS PrivateLink (only for AWS stacks)
  string pdc_gateway_private_connectivity_info_private_dns = 68 [
    json_name = "pdc_gateway_private_connectivity_info_private_dns"
  ];

  // Regions for PDC's Gateway when using AWS PrivateLink (only for AWS stacks)
  repeated string pdc_gateway_private_connectivity_info_regions = 69 [
    json_name = "pdc_gateway_private_connectivity_info_regions"
  ];

  // Service Name for PDC's Gateway when using AWS PrivateLink (only for AWS stacks)
  string pdc_gateway_private_connectivity_info_service_name = 70 [
    json_name = "pdc_gateway_private_connectivity_info_service_name"
  ];

  // Allowlist API endpoint that returns the source IP addresses to allow for the
  // Profiles instance.
  string profiles_allowlist_url = 71 [json_name = "profiles_allowlist_url"];

  // Comma-separated list of CNAMEs that can be whitelisted to access the Profiles
  // instance (Optional)
  string profiles_ip_allow_list_cname = 72 [json_name = "profiles_ip_allow_list_cname"];

  string profiles_name = 73 [json_name = "profiles_name"];

  // Availability Zone IDs for Profiles when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string profiles_private_connectivity_info_availability_zone_ids = 74 [
    json_name = "profiles_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for Profiles when using AWS PrivateLink (only for AWS stacks)
  repeated string profiles_private_connectivity_info_availability_zones = 75 [
    json_name = "profiles_private_connectivity_info_availability_zones"
  ];

  // Private DNS for Profiles when using AWS PrivateLink (only for AWS stacks)
  string profiles_private_connectivity_info_private_dns = 76 [
    json_name = "profiles_private_connectivity_info_private_dns"
  ];

  // Regions for Profiles when using AWS PrivateLink (only for AWS stacks)
  repeated string profiles_private_connectivity_info_regions = 77 [
    json_name = "profiles_private_connectivity_info_regions"
  ];

  // Service Name for Profiles when using AWS PrivateLink (only for AWS stacks)
  string profiles_private_connectivity_info_service_name = 78 [
    json_name = "profiles_private_connectivity_info_service_name"
  ];

  string profiles_status = 79 [json_name = "profiles_status"];

  string profiles_url = 80 [json_name = "profiles_url"];

  int64 profiles_user_id = 81 [json_name = "profiles_user_id"];

  // Allowlist API endpoint that returns the source IP addresses to allow for the
  // Prometheus instance.
  string prometheus_allowlist_url = 82 [json_name = "prometheus_allowlist_url"];

  // Comma-separated list of CNAMEs that can be whitelisted to access the Prometheus
  // instance (Optional)
  string prometheus_ip_allow_list_cname = 83 [json_name = "prometheus_ip_allow_list_cname"];

  // Prometheus name for this instance.
  string prometheus_name = 84 [json_name = "prometheus_name"];

  // Availability Zone IDs for Prometheus when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string prometheus_private_connectivity_info_availability_zone_ids = 85 [
    json_name = "prometheus_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for Prometheus when using AWS PrivateLink (only for AWS
  // stacks)
  repeated string prometheus_private_connectivity_info_availability_zones = 86 [
    json_name = "prometheus_private_connectivity_info_availability_zones"
  ];

  // Private DNS for Prometheus when using AWS PrivateLink (only for AWS stacks)
  string prometheus_private_connectivity_info_private_dns = 87 [
    json_name = "prometheus_private_connectivity_info_private_dns"
  ];

  // Regions for Prometheus when using AWS PrivateLink (only for AWS stacks)
  repeated string prometheus_private_connectivity_info_regions = 88 [
    json_name = "prometheus_private_connectivity_info_regions"
  ];

  // Service Name for Prometheus when using AWS PrivateLink (only for AWS stacks)
  string prometheus_private_connectivity_info_service_name = 89 [
    json_name = "prometheus_private_connectivity_info_service_name"
  ];

  // Use this URL to query hosted metrics data e.g. Prometheus data source in Grafana
  string prometheus_remote_endpoint = 90 [json_name = "prometheus_remote_endpoint"];

  // Use this URL to send prometheus metrics to Grafana cloud
  string prometheus_remote_write_endpoint = 91 [json_name = "prometheus_remote_write_endpoint"];

  // Prometheus status for this instance.
  string prometheus_status = 92 [json_name = "prometheus_status"];

  // Prometheus url for this instance.
  string prometheus_url = 93 [json_name = "prometheus_url"];

  // Prometheus user ID. Used for e.g. remote_write.
  int64 prometheus_user_id = 94 [json_name = "prometheus_user_id"];

  // Region slug to assign to this stack. Changing region will destroy the existing
  // stack and create a new one in the desired region. Use the region list API to get
  // the list of available regions:
  // com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-regions.
  string region_slug = 95 [json_name = "region_slug"];

  // Subdomain that the Grafana instance will be available at. Setting slug to
  // `<stack_slug>` will make the instance available at
  // `https://<stack_slug>.grafana.net`.
  string slug = 96;

  // Base URL of the Synthetic Monitoring API for this stack's region. This can be
  // used with the `sm_url` provider config option. Note: Synthetic Monitoring
  // requires activation either via the `grafana_synthetic_monitoring_installation`
  // resource or manually in the Grafana Cloud UI before it can be used.
  string sm_url = 97 [json_name = "sm_url"];

  // Status of the stack.
  string status = 98;

  // Allowlist API endpoint that returns the source IP addresses to allow for the
  // Traces instance.
  string traces_allowlist_url = 99 [json_name = "traces_allowlist_url"];

  // Comma-separated list of CNAMEs that can be whitelisted to access the Traces
  // instance (Optional)
  string traces_ip_allow_list_cname = 100 [json_name = "traces_ip_allow_list_cname"];

  string traces_name = 101 [json_name = "traces_name"];

  // Availability Zone IDs for Traces when using AWS PrivateLink (only for AWS stacks)
  repeated string traces_private_connectivity_info_availability_zone_ids = 102 [
    json_name = "traces_private_connectivity_info_availability_zone_ids"
  ];

  // Availability Zones for Traces when using AWS PrivateLink (only for AWS stacks)
  repeated string traces_private_connectivity_info_availability_zones = 103 [
    json_name = "traces_private_connectivity_info_availability_zones"
  ];

  // Private DNS for Traces when using AWS PrivateLink (only for AWS stacks)
  string traces_private_connectivity_info_private_dns = 104 [
    json_name = "traces_private_connectivity_info_private_dns"
  ];

  // Regions for Traces when using AWS PrivateLink (only for AWS stacks)
  repeated string traces_private_connectivity_info_regions = 105 [
    json_name = "traces_private_connectivity_info_regions"
  ];

  // Service Name for Traces when using AWS PrivateLink (only for AWS stacks)
  string traces_private_connectivity_info_service_name = 106 [
    json_name = "traces_private_connectivity_info_service_name"
  ];

  string traces_status = 107 [json_name = "traces_status"];

  // Base URL of the Traces instance configured for this stack. To use this in the
  // Tempo data source in Grafana, append `/tempo` to the URL.
  string traces_url = 108 [json_name = "traces_url"];

  int64 traces_user_id = 109 [json_name = "traces_user_id"];

  // Custom URL for the Grafana instance. Must have a CNAME setup to point to
  // `.grafana.net` before creating the stack
  string url = 110;

  // Whether to wait for readiness of the stack after creating it. The check is a HEAD
  // request to the stack URL (Grafana instance). Defaults to `true`.
  bool wait_for_readiness = 111 [json_name = "wait_for_readiness"];

  // How long to wait for readiness (if enabled). Defaults to `10m0s`.
  string wait_for_readiness_timeout = 112 [json_name = "wait_for_readiness_timeout"];

  google.protobuf.Value for_each = 113 [json_name = "for_each"];

  repeated string depends_on = 114 [json_name = "depends_on"];

  int32 count = 115;

  string provider = 116;

  terraform.v1.Lifecycle lifecycle = 117;
}

// GrafanaCloudStackServiceAccount version is 0
message GrafanaCloudStackServiceAccount {
  string id = 1;

  // The disabled status for the service account. Defaults to `false`.
  bool is_disabled = 2 [json_name = "is_disabled"];

  // The name of the service account.
  string name = 3;

  // The basic role of the service account in the organization.
  string role = 4;

  string stack_slug = 5 [json_name = "stack_slug"];

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;
}

// GrafanaCloudStackServiceAccountRotatingToken version is 0
message GrafanaCloudStackServiceAccountRotatingToken {
  // Deletes the service account token in Grafana when the resource is destroyed in
  // Terraform, instead of leaving it to expire at its `expiration` time. Use it with
  // `lifecycle { create_before_destroy = true }` to make sure that the new token is
  // created before the old one is deleted. Defaults to `false`.
  bool delete_on_destroy = 1 [json_name = "delete_on_destroy"];

  // Duration of the time window before expiring where the token can be rotated, in
  // seconds.
  int64 early_rotation_window_seconds = 2 [json_name = "early_rotation_window_seconds"];

  // The expiration date of the service account token.
  string expiration = 3;

  // The status of the service account token.
  bool has_expired = 4 [json_name = "has_expired"];

  string id = 5;

  // The key of the service account token.
  string key = 6;

  // The name of the service account token. It will start with `<name_prefix>-` and
  // will have characters appended to it to make the name unique.
  string name = 7;

  // Prefix for the name of the service account tokens created by this resource. The
  // actual name will be stored in the computed field `name`, which will be in the
  // format `<name_prefix>-<additional_characters>`.
  string name_prefix = 8 [json_name = "name_prefix"];

  // Signals that the service account token is expired or within the period to be
  // early rotated.
  bool ready_for_rotation = 9 [json_name = "ready_for_rotation"];

  // The token expiration in seconds.
  int64 seconds_to_live = 10 [json_name = "seconds_to_live"];

  // The ID of the service account to which the token belongs.
  string service_account_id = 11 [json_name = "service_account_id"];

  string stack_slug = 12 [json_name = "stack_slug"];

  google.protobuf.Value for_each = 13 [json_name = "for_each"];

  repeated string depends_on = 14 [json_name = "depends_on"];

  int32 count = 15;

  string provider = 16;

  terraform.v1.Lifecycle lifecycle = 17;
}

// GrafanaCloudStackServiceAccountToken version is 0
message GrafanaCloudStackServiceAccountToken {
  // The expiration date of the service account token.
  string expiration = 1;

  // The status of the service account token.
  bool has_expired = 2 [json_name = "has_expired"];

  string id = 3;

  // The key of the service account token.
  string key = 4;

  // The name of the service account token.
  string name = 5;

  // The key expiration in seconds. It is optional. If it is a positive number an
  // expiration date for the key is set. If it is null, zero or is omitted completely
  // (unless `api_key_max_seconds_to_live` configuration option is set) the key will
  // never expire.
  int64 seconds_to_live = 6 [json_name = "seconds_to_live"];

  // The ID of the service account to which the token belongs.
  string service_account_id = 7 [json_name = "service_account_id"];

  string stack_slug = 8 [json_name = "stack_slug"];

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}
