syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaK6Installation version is 0
message GrafanaK6Installation {
  // Deprecated: The [Grafana Cloud access
  // grafana-cloud/account-management/authentication-and-permissions/access-policies/)
  // token. It is no longer used to install the k6 App and can be safely removed.
  string cloud_access_policy_token = 1 [json_name = "cloud_access_policy_token"];

  // The [service
  // ccount](https://grafana.com/docs/grafana/latest/administration/service-accounts/)
  // token.
  string grafana_sa_token = 2 [json_name = "grafana_sa_token"];

  // The user to use for the installation.
  string grafana_user = 3 [json_name = "grafana_user"];

  string id = 4;

  // Generated token to access the k6 API.
  string k6_access_token = 5 [json_name = "k6_access_token"];

  // The Grafana Cloud k6 API url.
  string k6_api_url = 6 [json_name = "k6_api_url"];

  // The identifier of the k6 organization.
  string k6_organization = 7 [json_name = "k6_organization"];

  // The identifier of the stack to install k6 on.
  string stack_id = 8 [json_name = "stack_id"];

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}

// GrafanaK6LoadTest version is 1
message GrafanaK6LoadTest {
  // Identifier of a baseline test run used for results comparison.
  string baseline_test_run_id = 1 [json_name = "baseline_test_run_id"];

  // The date when the load test was created.
  string created = 2;

  // Numeric identifier of the load test.
  string id = 3;

  // Identifier of the k6 version used to run the test. If not set, the test is pinned
  // at creation to the current default major version established by Grafana Cloud.
  // Example: 2
  string k6_version = 4 [json_name = "k6_version"];

  // Human-friendly identifier of the load test.
  string name = 5;

  // The identifier of the project this load test belongs to.
  string project_id = 6 [json_name = "project_id"];

  // The k6 test script content. Can be provided inline or via the `file()` function.
  string script = 7;

  // The date when the load test was last updated.
  string updated = 8;

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}

// GrafanaK6Project version is 1
message GrafanaK6Project {
  // The date when the project was created.
  string created = 1;

  // The Grafana folder uid.
  string grafana_folder_uid = 2 [json_name = "grafana_folder_uid"];

  // Numeric identifier of the project.
  string id = 3;

  // Use this project as default for running tests when no explicit project identifier
  // is provided.
  bool is_default = 4 [json_name = "is_default"];

  // Human-friendly identifier of the project.
  string name = 5;

  // The date when the project was last updated.
  string updated = 6;

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// GrafanaK6ProjectAllowedLoadZones version is 0
message GrafanaK6ProjectAllowedLoadZones {
  // List of allowed private k6 load zone IDs for this project.
  repeated string allowed_load_zones = 1 [json_name = "allowed_load_zones"];

  // The identifier of the project. This is set to the same as the project_id.
  string id = 2;

  // The identifier of the project to manage private allowed load zones for.
  string project_id = 3 [json_name = "project_id"];

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;
}

// GrafanaK6ProjectLimits version is 1
message GrafanaK6ProjectLimits {
  // Maximum duration of a test in seconds.
  int64 duration_max_per_test = 1 [json_name = "duration_max_per_test"];

  // The identifier of the project limits. This is the same as the project_id.
  string id = 2;

  // The identifier of the project to manage limits for.
  string project_id = 3 [json_name = "project_id"];

  // Maximum number of concurrent browser virtual users (VUs) used in one test.
  int64 vu_browser_max_per_test = 4 [json_name = "vu_browser_max_per_test"];

  // Maximum number of concurrent virtual users (VUs) used in one test.
  int64 vu_max_per_test = 5 [json_name = "vu_max_per_test"];

  // Maximum amount of virtual user hours (VU/h) used per one calendar month.
  int64 vuh_max_per_month = 6 [json_name = "vuh_max_per_month"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// GrafanaK6Schedule version is 0
message GrafanaK6Schedule {
  // The email of the user who created the schedule.
  string created_by = 1 [json_name = "created_by"];

  // Whether the schedule is deactivated.
  bool deactivated = 2;

  // Numeric identifier of the schedule.
  string id = 3;

  // The identifier of the load test to schedule.
  string load_test_id = 4 [json_name = "load_test_id"];

  // The next scheduled execution time.
  string next_run = 5 [json_name = "next_run"];

  // The start time for the schedule (RFC3339 format).
  string starts = 6;

  repeated Cron cron = 7;

  repeated RecurrenceRule recurrence_rule = 8 [json_name = "recurrence_rule"];

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;

  message Cron {
    // A cron expression with exactly 5 entries, or an alias. The allowed aliases are:
    // `@yearly`, `@annually`, `@monthly`, `@weekly`, `@daily`, `@hourly`.
    string schedule = 1;

    // The timezone of the cron expression. For example, `UTC` or `Europe/London`.
    string timezone = 2;
  }

  message RecurrenceRule {
    // The weekdays when the 'WEEKLY' recurrence will be applied (e.g., ['MO', 'WE',
    // 'FR']). Cannot be set for other frequencies.
    repeated string byday = 1;

    // How many times the recurrence will repeat.
    int64 count = 2;

    // The frequency of the schedule (HOURLY, DAILY, WEEKLY, MONTHLY, YEARLY).
    string frequency = 3;

    // The interval between each frequency iteration (e.g., 2 = every 2 hours for
    // HOURLY). Defaults to 1.
    int64 interval = 4;

    // The end time for the recurrence (RFC3339 format).
    string until = 5;
  }
}
