syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaNotificationPolicy version is 0
message GrafanaNotificationPolicy {
  // The default contact point to route all unmatched notifications to.
  string contact_point = 1 [json_name = "contact_point"];

  // Allow modifying the notification policy from other sources than Terraform or the
  // Grafana API. Defaults to `false`.
  bool disable_provenance = 2 [json_name = "disable_provenance"];

  // A list of alert labels to group alerts into notifications by. Use the special
  // label `...` to group alerts by all labels, effectively disabling grouping.
  repeated string group_by = 3 [json_name = "group_by"];

  // Minimum time interval between two notifications for the same group. Default is 5
  // minutes.
  string group_interval = 4 [json_name = "group_interval"];

  // Time to wait to buffer alerts of the same group before sending a notification.
  // Default is 30 seconds.
  string group_wait = 5 [json_name = "group_wait"];

  string id = 6;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 7 [json_name = "org_id"];

  // Minimum time interval for re-sending a notification if an alert is still firing.
  // Default is 4 hours.
  string repeat_interval = 8 [json_name = "repeat_interval"];

  repeated Policy policy = 9;

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;

  message Policy {
    // A list of time interval names to apply to alerts that match this policy to
    // suppress them unless they are sent at the specified time. Supported in Grafana
    // 12.1.0 and later
    repeated string active_timings = 1 [json_name = "active_timings"];

    // The contact point to route notifications that match this rule to.
    string contact_point = 2 [json_name = "contact_point"];

    // Whether to continue matching subsequent rules if an alert matches the current
    // rule. Otherwise, the rule will be 'consumed' by the first policy to match it.
    bool continue = 3;

    // A list of alert labels to group alerts into notifications by. Use the special
    // label `...` to group alerts by all labels, effectively disabling grouping.
    // Required for root policy only. If empty, the parent grouping is used.
    repeated string group_by = 4 [json_name = "group_by"];

    // Minimum time interval between two notifications for the same group. Default is 5
    // minutes.
    string group_interval = 5 [json_name = "group_interval"];

    // Time to wait to buffer alerts of the same group before sending a notification.
    // Default is 30 seconds.
    string group_wait = 6 [json_name = "group_wait"];

    // A list of time intervals to apply to alerts that match this policy to mute them
    // for the specified time.
    repeated string mute_timings = 7 [json_name = "mute_timings"];

    // Minimum time interval for re-sending a notification if an alert is still firing.
    // Default is 4 hours.
    string repeat_interval = 8 [json_name = "repeat_interval"];

    repeated Matcher matcher = 9;

    repeated Policy policy = 10;

    message Matcher {
      // The name of the label to match against.
      string label = 1;

      // The operator to apply when matching values of the given label. Allowed operators
      // are `=` for equality, `!=` for negated equality, `=~` for regex equality, and
      // `!~` for negated regex equality.
      string match = 2;

      // The label value to match against.
      string value = 3;
    }

    message Policy {
      // A list of time interval names to apply to alerts that match this policy to
      // suppress them unless they are sent at the specified time. Supported in Grafana
      // 12.1.0 and later
      repeated string active_timings = 1 [json_name = "active_timings"];

      // The contact point to route notifications that match this rule to.
      string contact_point = 2 [json_name = "contact_point"];

      // Whether to continue matching subsequent rules if an alert matches the current
      // rule. Otherwise, the rule will be 'consumed' by the first policy to match it.
      bool continue = 3;

      // A list of alert labels to group alerts into notifications by. Use the special
      // label `...` to group alerts by all labels, effectively disabling grouping.
      // Required for root policy only. If empty, the parent grouping is used.
      repeated string group_by = 4 [json_name = "group_by"];

      // Minimum time interval between two notifications for the same group. Default is 5
      // minutes.
      string group_interval = 5 [json_name = "group_interval"];

      // Time to wait to buffer alerts of the same group before sending a notification.
      // Default is 30 seconds.
      string group_wait = 6 [json_name = "group_wait"];

      // A list of time intervals to apply to alerts that match this policy to mute them
      // for the specified time.
      repeated string mute_timings = 7 [json_name = "mute_timings"];

      // Minimum time interval for re-sending a notification if an alert is still firing.
      // Default is 4 hours.
      string repeat_interval = 8 [json_name = "repeat_interval"];

      repeated Matcher matcher = 9;

      repeated Policy policy = 10;

      message Matcher {
        // The name of the label to match against.
        string label = 1;

        // The operator to apply when matching values of the given label. Allowed operators
        // are `=` for equality, `!=` for negated equality, `=~` for regex equality, and
        // `!~` for negated regex equality.
        string match = 2;

        // The label value to match against.
        string value = 3;
      }

      message Policy {
        // A list of time interval names to apply to alerts that match this policy to
        // suppress them unless they are sent at the specified time. Supported in Grafana
        // 12.1.0 and later
        repeated string active_timings = 1 [json_name = "active_timings"];

        // The contact point to route notifications that match this rule to.
        string contact_point = 2 [json_name = "contact_point"];

        // Whether to continue matching subsequent rules if an alert matches the current
        // rule. Otherwise, the rule will be 'consumed' by the first policy to match it.
        bool continue = 3;

        // A list of alert labels to group alerts into notifications by. Use the special
        // label `...` to group alerts by all labels, effectively disabling grouping.
        // Required for root policy only. If empty, the parent grouping is used.
        repeated string group_by = 4 [json_name = "group_by"];

        // Minimum time interval between two notifications for the same group. Default is 5
        // minutes.
        string group_interval = 5 [json_name = "group_interval"];

        // Time to wait to buffer alerts of the same group before sending a notification.
        // Default is 30 seconds.
        string group_wait = 6 [json_name = "group_wait"];

        // A list of time intervals to apply to alerts that match this policy to mute them
        // for the specified time.
        repeated string mute_timings = 7 [json_name = "mute_timings"];

        // Minimum time interval for re-sending a notification if an alert is still firing.
        // Default is 4 hours.
        string repeat_interval = 8 [json_name = "repeat_interval"];

        repeated Matcher matcher = 9;

        repeated Policy policy = 10;

        message Matcher {
          // The name of the label to match against.
          string label = 1;

          // The operator to apply when matching values of the given label. Allowed operators
          // are `=` for equality, `!=` for negated equality, `=~` for regex equality, and
          // `!~` for negated regex equality.
          string match = 2;

          // The label value to match against.
          string value = 3;
        }

        message Policy {
          // A list of time interval names to apply to alerts that match this policy to
          // suppress them unless they are sent at the specified time. Supported in Grafana
          // 12.1.0 and later
          repeated string active_timings = 1 [json_name = "active_timings"];

          // The contact point to route notifications that match this rule to.
          string contact_point = 2 [json_name = "contact_point"];

          // Whether to continue matching subsequent rules if an alert matches the current
          // rule. Otherwise, the rule will be 'consumed' by the first policy to match it.
          bool continue = 3;

          // A list of alert labels to group alerts into notifications by. Use the special
          // label `...` to group alerts by all labels, effectively disabling grouping.
          // Required for root policy only. If empty, the parent grouping is used.
          repeated string group_by = 4 [json_name = "group_by"];

          // Minimum time interval between two notifications for the same group. Default is 5
          // minutes.
          string group_interval = 5 [json_name = "group_interval"];

          // Time to wait to buffer alerts of the same group before sending a notification.
          // Default is 30 seconds.
          string group_wait = 6 [json_name = "group_wait"];

          // A list of time intervals to apply to alerts that match this policy to mute them
          // for the specified time.
          repeated string mute_timings = 7 [json_name = "mute_timings"];

          // Minimum time interval for re-sending a notification if an alert is still firing.
          // Default is 4 hours.
          string repeat_interval = 8 [json_name = "repeat_interval"];

          repeated Matcher matcher = 9;

          repeated Policy policy = 10;

          message Matcher {
            // The name of the label to match against.
            string label = 1;

            // The operator to apply when matching values of the given label. Allowed operators
            // are `=` for equality, `!=` for negated equality, `=~` for regex equality, and
            // `!~` for negated regex equality.
            string match = 2;

            // The label value to match against.
            string value = 3;
          }

          message Policy {
            // A list of time interval names to apply to alerts that match this policy to
            // suppress them unless they are sent at the specified time. Supported in Grafana
            // 12.1.0 and later
            repeated string active_timings = 1 [json_name = "active_timings"];

            // The contact point to route notifications that match this rule to.
            string contact_point = 2 [json_name = "contact_point"];

            // Whether to continue matching subsequent rules if an alert matches the current
            // rule. Otherwise, the rule will be 'consumed' by the first policy to match it.
            bool continue = 3;

            // A list of alert labels to group alerts into notifications by. Use the special
            // label `...` to group alerts by all labels, effectively disabling grouping.
            // Required for root policy only. If empty, the parent grouping is used.
            repeated string group_by = 4 [json_name = "group_by"];

            // Minimum time interval between two notifications for the same group. Default is 5
            // minutes.
            string group_interval = 5 [json_name = "group_interval"];

            // Time to wait to buffer alerts of the same group before sending a notification.
            // Default is 30 seconds.
            string group_wait = 6 [json_name = "group_wait"];

            // A list of time intervals to apply to alerts that match this policy to mute them
            // for the specified time.
            repeated string mute_timings = 7 [json_name = "mute_timings"];

            // Minimum time interval for re-sending a notification if an alert is still firing.
            // Default is 4 hours.
            string repeat_interval = 8 [json_name = "repeat_interval"];

            repeated Matcher matcher = 9;

            message Matcher {
              // The name of the label to match against.
              string label = 1;

              // The operator to apply when matching values of the given label. Allowed operators
              // are `=` for equality, `!=` for negated equality, `=~` for regex equality, and
              // `!~` for negated regex equality.
              string match = 2;

              // The label value to match against.
              string value = 3;
            }
          }
        }
      }
    }
  }
}
