syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaOncallEscalation version is 0
message GrafanaOncallEscalation {
  // The ID of an Action for trigger_webhook type step.
  string action_to_trigger = 1 [json_name = "action_to_trigger"];

  // The duration of delay for wait type step. (60-86400) seconds
  int64 duration = 2;

  // The ID of the escalation chain.
  string escalation_chain_id = 3 [json_name = "escalation_chain_id"];

  // The ID of a User Group for notify_user_group type step.
  string group_to_notify = 4 [json_name = "group_to_notify"];

  string id = 5;

  // Will activate "important" personal notification rules. Actual for steps:
  // notify_persons, notify_person_next_each_time, notify_on_call_from_schedule,
  // notify_next_on_call_from_schedule, notify_user_group and notify_team_members
  bool important = 6;

  // The beginning of the time interval for notify_if_time_from_to type step in UTC
  // (for example 08:00:00Z).
  string notify_if_time_from = 7 [json_name = "notify_if_time_from"];

  // The end of the time interval for notify_if_time_from_to type step in UTC (for
  // example 18:00:00Z).
  string notify_if_time_to = 8 [json_name = "notify_if_time_to"];

  // ID of a Schedule for notify_on_call_from_schedule or
  // notify_next_on_call_from_schedule type step.
  string notify_on_call_from_schedule = 9 [json_name = "notify_on_call_from_schedule"];

  // The ID of a Team for a notify_team_members type step.
  string notify_to_team_members = 10 [json_name = "notify_to_team_members"];

  // Number of alerts that must occur within the time window to continue escalation
  // for notify_if_num_alerts_in_window type step.
  int64 num_alerts_in_window = 11 [json_name = "num_alerts_in_window"];

  // Time window in minutes to count alerts for notify_if_num_alerts_in_window type
  // step.
  int64 num_minutes_in_window = 12 [json_name = "num_minutes_in_window"];

  // The list of ID's of users for notify_persons type step.
  repeated string persons_to_notify = 13 [json_name = "persons_to_notify"];

  // The list of ID's of users for notify_person_next_each_time type step.
  repeated string persons_to_notify_next_each_time = 14 [json_name = "persons_to_notify_next_each_time"];

  // The position of the escalation step (starts from 0).
  int64 position = 15;

  // The severity of the incident for declare_incident type step.
  string severity = 16;

  // The type of escalation policy. Can be wait, notify_persons,
  // notify_person_next_each_time, notify_on_call_from_schedule,
  // notify_next_on_call_from_schedule, trigger_webhook, notify_user_group, resolve,
  // notify_whole_channel, notify_if_time_from_to, notify_if_num_alerts_in_window,
  // repeat_escalation, notify_team_members, declare_incident
  string type = 17;

  google.protobuf.Value for_each = 18 [json_name = "for_each"];

  repeated string depends_on = 19 [json_name = "depends_on"];

  int32 count = 20;

  string provider = 21;

  terraform.v1.Lifecycle lifecycle = 22;
}

// GrafanaOncallEscalationChain version is 0
message GrafanaOncallEscalationChain {
  string id = 1;

  // The name of the escalation chain.
  string name = 2;

  // The ID of the OnCall team (using the `grafana_oncall_team` datasource).
  string team_id = 3 [json_name = "team_id"];

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;
}

// GrafanaOncallIntegration version is 0
message GrafanaOncallIntegration {
  // A list of string-to-string mappings for dynamic labels. Each map must include one
  // key named "key" and one key named "value" (using the `grafana_oncall_label`
  // datasource).
  repeated string dynamic_labels = 1 [json_name = "dynamic_labels"];

  string id = 2;

  // The inbound email address for the integration. Only available for integration
  // type `inbound_email`.
  string inbound_email = 3 [json_name = "inbound_email"];

  // A list of string-to-string mappings for static labels. Each map must include one
  // key named "key" and one key named "value" (using the `grafana_oncall_label`
  // datasource).
  repeated string labels = 4;

  // The link for using in an integrated tool.
  string link = 5;

  // The name of the service integration.
  string name = 6;

  // The ID of the OnCall team (using the `grafana_oncall_team` datasource).
  string team_id = 7 [json_name = "team_id"];

  // The type of integration. Can be grafana, grafana_alerting, webhook, alertmanager,
  // kapacitor, fabric, newrelic, datadog, pagerduty, pingdom, elastalert, amazon_sns,
  // curler, sentry, formatted_webhook, stackdriver, uptimerobot, sentry, zabbix,
  // prtg, inbound_email, direct_paging, jira, zendesk.
  string type = 8;

  DefaultRoute default_route = 9 [json_name = "default_route"];

  Templates templates = 10;

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;

  message DefaultRoute {
    // The ID of the escalation chain.
    string escalation_chain_id = 1 [json_name = "escalation_chain_id"];

    string id = 2;

    Msteams msteams = 3;

    Slack slack = 4;

    Telegram telegram = 5;

    message Msteams {
      // Enable notification in MS teams. Defaults to `true`.
      bool enabled = 1;

      // MS teams channel id. Alerts will be directed to this channel in Microsoft teams.
      string id = 2;
    }

    message Slack {
      // Slack channel id. Alerts will be directed to this channel in Slack.
      string channel_id = 1 [json_name = "channel_id"];

      // Enable notification in Slack. Defaults to `true`.
      bool enabled = 2;
    }

    message Telegram {
      // Enable notification in Telegram. Defaults to `true`.
      bool enabled = 1;

      // Telegram channel id. Alerts will be directed to this channel in Telegram.
      string id = 2;
    }
  }

  message Templates {
    // Template for sending a signal to acknowledge the Incident.
    string acknowledge_signal = 1 [json_name = "acknowledge_signal"];

    // Template for the key by which alerts are grouped.
    string grouping_key = 2 [json_name = "grouping_key"];

    // Template for sending a signal to resolve the Incident.
    string resolve_signal = 3 [json_name = "resolve_signal"];

    // Template for a source link.
    string source_link = 4 [json_name = "source_link"];

    Email email = 5;

    MicrosoftTeams microsoft_teams = 6 [json_name = "microsoft_teams"];

    MobileApp mobile_app = 7 [json_name = "mobile_app"];

    PhoneCall phone_call = 8 [json_name = "phone_call"];

    Slack slack = 9;

    Sms sms = 10;

    Telegram telegram = 11;

    Web web = 12;

    message Email {
      // Template for Alert message.
      string message = 1;

      // Template for Alert title.
      string title = 2;
    }

    message MicrosoftTeams {
      // Template for Alert image url.
      string image_url = 1 [json_name = "image_url"];

      // Template for Alert message.
      string message = 2;

      // Template for Alert title.
      string title = 3;
    }

    message MobileApp {
      // Template for Alert message.
      string message = 1;

      // Template for Alert title.
      string title = 2;
    }

    message PhoneCall {
      // Template for Alert title.
      string title = 1;
    }

    message Slack {
      // Template for Alert image url.
      string image_url = 1 [json_name = "image_url"];

      // Template for Alert message.
      string message = 2;

      // Template for Alert title.
      string title = 3;
    }

    message Sms {
      // Template for Alert title.
      string title = 1;
    }

    message Telegram {
      // Template for Alert image url.
      string image_url = 1 [json_name = "image_url"];

      // Template for Alert message.
      string message = 2;

      // Template for Alert title.
      string title = 3;
    }

    message Web {
      // Template for Alert image url.
      string image_url = 1 [json_name = "image_url"];

      // Template for Alert message.
      string message = 2;

      // Template for Alert title.
      string title = 3;
    }
  }
}

// GrafanaOncallOnCallShift version is 0
message GrafanaOncallOnCallShift {
  // This parameter takes a list of days in iCal format. Can be MO, TU, WE, TH, FR,
  // SA, SU
  repeated string by_day = 1 [json_name = "by_day"];

  // This parameter takes a list of months. Valid values are 1 to 12
  repeated int64 by_month = 2 [json_name = "by_month"];

  // This parameter takes a list of days of the month.  Valid values are 1 to 31 or
  // -31 to -1
  repeated int64 by_monthday = 3 [json_name = "by_monthday"];

  // The duration of the event.
  int64 duration = 4;

  // The frequency of the event. Can be hourly, daily, weekly, monthly
  string frequency = 5;

  string id = 6;

  // The positive integer representing at which intervals the recurrence rule repeats.
  int64 interval = 7;

  // The priority level. The higher the value, the higher the priority.
  int64 level = 8;

  // The shift's name.
  string name = 9;

  // The list of lists with on-call users (for rolling_users event type)
  repeated string rolling_users = 10 [json_name = "rolling_users"];

  // The start time of the on-call shift. This parameter takes a date format as
  // yyyy-MM-dd'T'HH:mm:ss (for example "2020-09-05T08:00:00")
  string start = 11;

  // The index of the list of users in rolling_users, from which on-call rotation
  // starts.
  int64 start_rotation_from_user_index = 12 [json_name = "start_rotation_from_user_index"];

  // The ID of the OnCall team (using the `grafana_oncall_team` datasource).
  string team_id = 13 [json_name = "team_id"];

  // The shift's timezone.  Overrides schedule's timezone.
  string time_zone = 14 [json_name = "time_zone"];

  // The shift's type. Can be rolling_users, recurrent_event, single_event
  string type = 15;

  // The end time of recurrent on-call shifts (endless if null). This parameter takes
  // a date format as yyyy-MM-dd'T'HH:mm:ss (for example "2020-09-05T08:00:00")
  string until = 16;

  // The list of on-call users (for single_event and recurrent_event event type).
  repeated string users = 17;

  // Start day of the week in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
  string week_start = 18 [json_name = "week_start"];

  google.protobuf.Value for_each = 19 [json_name = "for_each"];

  repeated string depends_on = 20 [json_name = "depends_on"];

  int32 count = 21;

  string provider = 22;

  terraform.v1.Lifecycle lifecycle = 23;
}

// GrafanaOncallOutgoingWebhook version is 0
message GrafanaOncallOutgoingWebhook {
  // The auth data of the webhook. Used in Authorization header instead of
  // user/password auth.
  string authorization_header = 1 [json_name = "authorization_header"];

  // The data of the webhook.
  string data = 2;

  // Toggle to send the entire webhook payload instead of using the values in the Data
  // field.
  bool forward_whole_payload = 3 [json_name = "forward_whole_payload"];

  // Headers to add to the outgoing webhook request.
  string headers = 4;

  // The HTTP method used in the request made by the outgoing webhook. Defaults to
  // `POST`.
  string http_method = 5 [json_name = "http_method"];

  string id = 6;

  // Restricts the outgoing webhook to only trigger if the event came from a selected
  // integration. If no integrations are selected the outgoing webhook will trigger
  // for any integration.
  repeated string integration_filter = 7 [json_name = "integration_filter"];

  // Controls whether the outgoing webhook will trigger or is ignored. Defaults to
  // `true`.
  bool is_webhook_enabled = 8 [json_name = "is_webhook_enabled"];

  // The name of the outgoing webhook.
  string name = 9;

  // The auth data of the webhook. Used for Basic authentication
  string password = 10;

  // The preset of the outgoing webhook. Possible values are: `simple_webhook`,
  // `advanced_webhook`, `grafana_sift`, `grafana_assistant`, `incident_webhook`. If
  // no preset is set, the default preset is `advanced_webhook`.
  string preset = 11;

  // The ID of the OnCall team (using the `grafana_oncall_team` datasource).
  string team_id = 12 [json_name = "team_id"];

  // A template used to dynamically determine whether the webhook should execute based
  // on the content of the payload.
  string trigger_template = 13 [json_name = "trigger_template"];

  // The type of event that will cause this outgoing webhook to execute. The events
  // available will depend on the preset used. For alert group webhooks, the possible
  // triggers are: `escalation`, `alert group created`, `status change`,
  // `acknowledge`, `resolve`, `silence`, `unsilence`, `unresolve`, `unacknowledge`,
  // `resolution note added`, `personal notification`; for incident webhooks:
  // `incident declared`, `incident changed`, `incident resolved`. Defaults to
  // `escalation`.
  string trigger_type = 14 [json_name = "trigger_type"];

  // The webhook URL. Required when not using a preset that controls this field.
  string url = 15;

  // Username to use when making the outgoing webhook request.
  string user = 16;

  google.protobuf.Value for_each = 17 [json_name = "for_each"];

  repeated string depends_on = 18 [json_name = "depends_on"];

  int32 count = 19;

  string provider = 20;

  terraform.v1.Lifecycle lifecycle = 21;
}

// GrafanaOncallRoute version is 0
message GrafanaOncallRoute {
  // The ID of the escalation chain. Omit or set to null for a route with no
  // escalation chain.
  string escalation_chain_id = 1 [json_name = "escalation_chain_id"];

  string id = 2;

  // The ID of the integration.
  string integration_id = 3 [json_name = "integration_id"];

  // The position of the route (starts from 0).
  int64 position = 4;

  // Python Regex query. Route is chosen for an alert if there is a match inside the
  // alert payload.
  string routing_regex = 5 [json_name = "routing_regex"];

  // The type of route. Can be jinja2, regex Defaults to `regex`.
  string routing_type = 6 [json_name = "routing_type"];

  Msteams msteams = 7;

  Slack slack = 8;

  Telegram telegram = 9;

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;

  message Msteams {
    // Enable notification in MS teams. Defaults to `true`.
    bool enabled = 1;

    // MS teams channel id. Alerts will be directed to this channel in Microsoft teams.
    string id = 2;
  }

  message Slack {
    // Slack channel id. Alerts will be directed to this channel in Slack.
    string channel_id = 1 [json_name = "channel_id"];

    // Enable notification in Slack. Defaults to `true`.
    bool enabled = 2;
  }

  message Telegram {
    // Enable notification in Telegram. Defaults to `true`.
    bool enabled = 1;

    // Telegram channel id. Alerts will be directed to this channel in Telegram.
    string id = 2;
  }
}

// GrafanaOncallSchedule version is 0
message GrafanaOncallSchedule {
  // Enable overrides via web UI (it will ignore ical_url_overrides).
  bool enable_web_overrides = 1 [json_name = "enable_web_overrides"];

  // The URL of external iCal calendar which override primary events.
  string ical_url_overrides = 2 [json_name = "ical_url_overrides"];

  // The URL of the external calendar iCal file.
  string ical_url_primary = 3 [json_name = "ical_url_primary"];

  string id = 4;

  // The schedule's name.
  string name = 5;

  // The list of ID's of on-call shifts.
  repeated string shifts = 6;

  // The ID of the OnCall team (using the `grafana_oncall_team` datasource).
  string team_id = 7 [json_name = "team_id"];

  // The schedule's time zone.
  string time_zone = 8 [json_name = "time_zone"];

  // The schedule's type. Valid values are `ical`, `calendar`, `web`.
  string type = 9;

  Slack slack = 10;

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;

  message Slack {
    // Slack channel id. Reminder about schedule shifts will be directed to this channel
    // in Slack.
    string channel_id = 1 [json_name = "channel_id"];

    // Slack user group id. Members of user group will be updated when on-call users
    // change.
    string user_group_id = 2 [json_name = "user_group_id"];
  }
}

// GrafanaOncallUserNotificationRule version is 0
message GrafanaOncallUserNotificationRule {
  // A time in seconds to wait (when `type=wait`). Can be 60, 300, 900, 1800, 3600
  int64 duration = 1;

  string id = 2;

  // Boolean value which indicates if a rule is “important”
  bool important = 3;

  // Personal notification rules execute one after another starting from position=0. A
  // new escalation policy created with a position of an existing escalation policy
  // will move the old one (and all following) down on the list.
  int64 position = 4;

  // The type of notification rule. Can be wait, notify_by_slack, notify_by_msteams,
  // notify_by_sms, notify_by_phone_call, notify_by_telegram, notify_by_email,
  // notify_by_mobile_app, notify_by_mobile_app_critical. NOTE: `notify_by_msteams` is
  // only available for Grafana Cloud customers.
  string type = 5;

  // User ID
  string user_id = 6 [json_name = "user_id"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}
