syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaOrganization version is 0
message GrafanaOrganization {
  // The login name of the configured default admin user for the Grafana
  //
  // installation. If unset, this value defaults to admin, the Grafana default.
  //
  // Grafana adds the default admin user to all organizations automatically upon
  //
  // creation, and this parameter keeps Terraform from removing it from
  //
  // organizations.
  //
  // Defaults to `admin`.
  string admin_user = 1 [json_name = "admin_user"];

  // A list of email addresses corresponding to users who should be given admin
  //
  // access to the organization. Note: users specified here must already exist in
  //
  // Grafana unless 'create_users' is set to true.
  repeated string admins = 2;

  // Whether or not to create Grafana users specified in the organization's
  //
  // membership if they don't already exist in Grafana. If unspecified, this
  //
  // parameter defaults to true, creating placeholder users with the name, login,
  //
  // and email set to the email of the user, and a random password. Setting this
  //
  // option to false will cause an error to be thrown for any users that do not
  //
  // already exist in Grafana.
  //
  // Defaults to `true`.
  bool create_users = 3 [json_name = "create_users"];

  // A list of email addresses corresponding to users who should be given editor
  //
  // access to the organization. Note: users specified here must already exist in
  //
  // Grafana unless 'create_users' is set to true.
  repeated string editors = 4;

  string id = 5;

  // The display name for the Grafana organization created.
  string name = 6;

  // The organization id assigned to this organization by Grafana.
  int64 org_id = 7 [json_name = "org_id"];

  // A list of email addresses corresponding to users who should be given none access
  // to the organization.
  //
  // Note: users specified here must already exist in Grafana, unless 'create_users'
  // is
  //
  // set to true. This feature is only available in Grafana 10.2+.
  repeated string users_without_access = 8 [json_name = "users_without_access"];

  // A list of email addresses corresponding to users who should be given viewer
  //
  // access to the organization. Note: users specified here must already exist in
  //
  // Grafana unless 'create_users' is set to true.
  repeated string viewers = 9;

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;
}

// GrafanaOrganizationPreferences version is 0
message GrafanaOrganizationPreferences {
  // The Organization home dashboard UID. This is only available in Grafana 9.0+.
  string home_dashboard_uid = 1 [json_name = "home_dashboard_uid"];

  string id = 2;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 3 [json_name = "org_id"];

  // The Organization theme. Any string value is supported, including custom themes.
  // Common values are `light`, `dark`, `system`, or an empty string for the default.
  string theme = 4;

  // The Organization timezone. Any string value is supported, including IANA timezone
  // names. Common values are `utc`, `browser`, or an empty string for the default.
  string timezone = 5;

  // The Organization week start day. Available values are `sunday`, `monday`,
  // `saturday`, or an empty string for the default. Defaults to ``.
  string week_start = 6 [json_name = "week_start"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}
