syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaPlaylist version is 0
message GrafanaPlaylist {
  // The ID of this resource.
  string id = 1;

  string interval = 2;

  // The name of the playlist.
  string name = 3;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 4 [json_name = "org_id"];

  repeated Item item = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;

  message Item {
    string id = 1;

    int64 order = 2;

    string type = 3;

    string value = 4;
  }
}
