syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaRuleGroup version is 0
message GrafanaRuleGroup {
  // Allow modifying the rule group from other sources than Terraform or the Grafana
  // API. Defaults to `false`.
  bool disable_provenance = 1 [json_name = "disable_provenance"];

  // The UID of the folder that the group belongs to.
  string folder_uid = 2 [json_name = "folder_uid"];

  string id = 3;

  // The interval, in seconds, at which all rules in the group are evaluated. If a
  // group contains many rules, the rules are evaluated sequentially.
  int64 interval_seconds = 4 [json_name = "interval_seconds"];

  // The name of the rule group.
  string name = 5;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 6 [json_name = "org_id"];

  repeated Rule rule = 7;

  google.protobuf.Value for_each = 8 [json_name = "for_each"];

  repeated string depends_on = 9 [json_name = "depends_on"];

  int32 count = 10;

  string provider = 11;

  terraform.v1.Lifecycle lifecycle = 12;

  message Rule {
    // Key-value pairs of metadata to attach to the alert rule. They add additional
    // information, such as a `summary` or `runbook_url`, to help identify and
    // investigate alerts. The `__dashboardUid__` and `__panelId__` annotations, which
    // link alerts to a panel, must be set together. Defaults to `map[]`.
    map<string, string> annotations = 1;

    // The `ref_id` of the query node in the `data` field to use as the alert condition.
    string condition = 2;

    // Describes what state to enter when the rule's query is invalid and the rule
    // cannot be executed. Options are OK, Error, KeepLast, and Alerting.  Defaults to
    // Alerting if not set.
    string exec_err_state = 3 [json_name = "exec_err_state"];

    // The amount of time for which the rule must be breached for the rule to be
    // considered to be Firing. Before this time has elapsed, the rule is only
    // considered to be Pending. Defaults to `0`.
    string for = 4;

    // Sets whether the alert should be paused or not. Defaults to `false`.
    bool is_paused = 5 [json_name = "is_paused"];

    // The amount of time for which the rule will considered to be Recovering after
    // initially Firing. Before this time has elapsed, the rule will continue to fire
    // once it's been triggered.
    string keep_firing_for = 6 [json_name = "keep_firing_for"];

    // Key-value pairs to attach to the alert rule that can be used in matching,
    // grouping, and routing. Defaults to `map[]`.
    map<string, string> labels = 7;

    // The number of missing series evaluations that must occur before the rule is
    // considered to be resolved.
    int64 missing_series_evals_to_resolve = 8 [json_name = "missing_series_evals_to_resolve"];

    // The name of the alert rule.
    string name = 9;

    // Describes what state to enter when the rule's query returns No Data. Options are
    // OK, NoData, KeepLast, and Alerting. Defaults to NoData if not set.
    string no_data_state = 10 [json_name = "no_data_state"];

    // The unique identifier of the alert rule.
    string uid = 11;

    repeated Data data = 12;

    NotificationSettings notification_settings = 13 [json_name = "notification_settings"];

    Record record = 14;

    message Data {
      // The UID of the datasource being queried, or "-100" if this stage is an expression
      // stage.
      string datasource_uid = 1 [json_name = "datasource_uid"];

      // Custom JSON data to send to the specified datasource when querying.
      string model = 2;

      // An optional identifier for the type of query being executed. Defaults to ``.
      string query_type = 3 [json_name = "query_type"];

      // A unique string to identify this query stage within a rule.
      string ref_id = 4 [json_name = "ref_id"];

      RelativeTimeRange relative_time_range = 5 [json_name = "relative_time_range"];

      message RelativeTimeRange {
        // The number of seconds in the past, relative to when the rule is evaluated, at
        // which the time range begins.
        int64 from = 1;

        // The number of seconds in the past, relative to when the rule is evaluated, at
        // which the time range ends.
        int64 to = 2;
      }
    }

    message NotificationSettings {
      // A list of time interval names to apply to alerts that match this policy to
      // suppress them unless they are sent at the specified time. Supported in Grafana
      // 12.1.0 and later
      repeated string active_timings = 1 [json_name = "active_timings"];

      // The contact point to route notifications that match this rule to.
      string contact_point = 2 [json_name = "contact_point"];

      // A list of alert labels to group alerts into notifications by. Use the special
      // label `...` to group alerts by all labels, effectively disabling grouping. If
      // empty, no grouping is used. If specified, requires labels 'alertname' and
      // 'grafana_folder' to be included.
      repeated string group_by = 3 [json_name = "group_by"];

      // Minimum time interval between two notifications for the same group. Default is 5
      // minutes.
      string group_interval = 4 [json_name = "group_interval"];

      // Time to wait to buffer alerts of the same group before sending a notification.
      // Default is 30 seconds.
      string group_wait = 5 [json_name = "group_wait"];

      // A list of mute timing names to apply to alerts that match this policy.
      repeated string mute_timings = 6 [json_name = "mute_timings"];

      // Minimum time interval for re-sending a notification if an alert is still firing.
      // Default is 4 hours.
      string repeat_interval = 7 [json_name = "repeat_interval"];
    }

    message Record {
      // The ref id of the query node in the data field to use as the source of the
      // metric.
      string from = 1;

      // The name of the metric to write to.
      string metric = 2;

      // The UID of the datasource to write the metric to.
      string target_datasource_uid = 3 [json_name = "target_datasource_uid"];
    }
  }
}
