syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.datasources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaDashboard version is 0
message GrafanaDashboard {
  // The complete dashboard model JSON.
  string config_json = 1 [json_name = "config_json"];

  // The numerical ID of the Grafana dashboard. Specify either this or `uid`. Defaults
  // to `-1`.
  int64 dashboard_id = 2 [json_name = "dashboard_id"];

  // The UID of the folder where the Grafana dashboard is found.
  string folder_uid = 3 [json_name = "folder_uid"];

  string id = 4;

  // Whether or not the Grafana dashboard is starred. Starred Dashboards will show up
  // on your own Home Dashboard by default, and are a convenient way to mark
  // Dashboards that you’re interested in.
  bool is_starred = 5 [json_name = "is_starred"];

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 6 [json_name = "org_id"];

  // URL slug of the dashboard (deprecated).
  string slug = 7;

  // The title of the Grafana dashboard.
  string title = 8;

  // The uid of the Grafana dashboard. Specify either this or `dashboard_id`. Defaults
  // to ``.
  string uid = 9;

  // The full URL of the dashboard.
  string url = 10;

  // The numerical version of the Grafana dashboard.
  int64 version = 11;

  google.protobuf.Value for_each = 12 [json_name = "for_each"];

  repeated string depends_on = 13 [json_name = "depends_on"];

  int32 count = 14;

  string provider = 15;

  terraform.v1.Lifecycle lifecycle = 16;
}
