syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.datasources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaFolder version is 0
message GrafanaFolder {
  string id = 1;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 2 [json_name = "org_id"];

  // The uid of the parent folder. If set, the folder will be nested. If not set, the
  // folder will be created in the root folder. Note: This requires the nestedFolders
  // feature flag to be enabled on your Grafana instance.
  string parent_folder_uid = 3 [json_name = "parent_folder_uid"];

  // The title of the folder. If not set, only the uid is used to find the folder.
  string title = 4;

  // The uid of the folder. If not set, only the title of the folder is used to find
  // the folder.
  string uid = 5;

  // The full URL of the folder.
  string url = 6;

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}
