syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.datasources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaServiceAccount version is 0
message GrafanaServiceAccount {
  // The ID of this resource.
  string id = 1;

  // The disabled status for the service account.
  bool is_disabled = 2 [json_name = "is_disabled"];

  // The name of the Service Account.
  string name = 3;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 4 [json_name = "org_id"];

  // The basic role of the service account in the organization.
  string role = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;
}
