syntax = "proto3";

// Provider: kubernetes 3
package terraform.kubernetes.datasources.v3;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// KubernetesServerVersion version is 0
message KubernetesServerVersion {
  // Kubernetes server build date
  string build_date = 1 [json_name = "build_date"];

  // Compiler used to build Kubernetes
  string compiler = 2;

  // Git commit SHA
  string git_commit = 3 [json_name = "git_commit"];

  // Git commit tree state
  string git_tree_state = 4 [json_name = "git_tree_state"];

  // Composite version and git commit sha
  string git_version = 5 [json_name = "git_version"];

  // Go compiler version
  string go_version = 6 [json_name = "go_version"];

  string id = 7;

  // Major Kubernetes version
  string major = 8;

  // Minor Kubernetes version
  string minor = 9;

  // Platform
  string platform = 10;

  // Composite Kubernetes server version
  string version = 11;

  google.protobuf.Value for_each = 12 [json_name = "for_each"];

  repeated string depends_on = 13 [json_name = "depends_on"];

  int32 count = 14;

  string provider = 15;

  terraform.v1.Lifecycle lifecycle = 16;
}
