syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaMessageTemplate version is 0
message GrafanaMessageTemplate {
  // Allow modifying the message template from other sources than Terraform or the
  // Grafana API. Defaults to `false`.
  bool disable_provenance = 1 [json_name = "disable_provenance"];

  // The ID of this resource.
  string id = 2;

  // The name of the notification template group.
  string name = 3;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 4 [json_name = "org_id"];

  // The content of the notification template group.
  string template = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;
}
