syntax = "proto3";

// Provider: grafana 4
package terraform.grafana.resources.v4;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// GrafanaMuteTiming version is 0
message GrafanaMuteTiming {
  // Allow modifying the mute timing from other sources than Terraform or the Grafana
  // API. Defaults to `false`.
  bool disable_provenance = 1 [json_name = "disable_provenance"];

  string id = 2;

  // The name of the mute timing.
  string name = 3;

  // The Organization ID. If not set, the Org ID defined in the provider block will be
  // used.
  string org_id = 4 [json_name = "org_id"];

  repeated Intervals intervals = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;

  message Intervals {
    // An inclusive range of days, 1-31, within a month, e.g. "1" or "14:16". Negative
    // values can be used to represent days counting from the end of a month, e.g. "-1".
    repeated string days_of_month = 1 [json_name = "days_of_month"];

    // Provides the time zone for the time interval. Must be a location in the IANA time
    // zone database, e.g "America/New_York"
    string location = 2;

    // An inclusive range of months, either numerical or full calendar month, e.g.
    // "1:3", "december", or "may:august".
    repeated string months = 3;

    // An inclusive range of weekdays, e.g. "monday" or "tuesday:thursday".
    repeated string weekdays = 4;

    // A positive inclusive range of years, e.g. "2030" or "2025:2026".
    repeated string years = 5;

    repeated Times times = 6;

    message Times {
      // The time, in hh:mm format, of when the interval should end exclusively.
      string end = 1;

      // The time, in hh:mm format, of when the interval should begin inclusively.
      string start = 2;
    }
  }
}
